### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by juzjus10** [rogerxiii/warframe-lua-disassembled#3]
Does this work in steam version?

**Comment by rogerxiii** [comment]
This is updated until Hotfix 28.0.7 of the steam version.

**Comment by juzjus10** [comment]
How do u inject this to warframe currently? I donwloaded gudov's injector
but the hooks are outdated

**Comment by rogerxiii** [comment]
You don't "inject" this. These are the game's lua files for you to reverse so you can write your own scripts.
